development:
  adapter: sqlite3
  database: db/development.sqlite3

production:
  database: d7um8dcv8nlklf
  adapter: postgresql
  username: vabxxrwbaeuutm
  host: ec2-54-204-241-136.compute-1.amazonaws.com
  password: 5b275eb90a9f552959b823b6c7cafcf2200e11c6d955ea781d453de8fa491f69
  
